import os
import json
import glob
from collections import defaultdict
from datetime import datetime
from tokenizers import Tokenizer
from tabulate import tabulate

def main():
    print("Loading Qwen2.5-7B tokenizer...")
    tok = Tokenizer.from_pretrained('Qwen/Qwen2.5-7B')

    def count_tok(text):
        if not text:
            return 0
        if not isinstance(text, str):
            text = str(text)
        return len(tok.encode(text, add_special_tokens=False).ids)

    brain_dir = os.path.expanduser('~/.gemini/antigravity/brain')
    convos = [d for d in os.listdir(brain_dir) if os.path.isdir(os.path.join(brain_dir, d))]
    print(f"Found {len(convos)} total conversation directories in brain/.")

    # Data structures for aggregation
    # By date: { 'YYYY-MM-DD': { 'sessions': set(), 'user_tok': 0, 'model_tok': 0, 'thinking_tok': 0, 'tool_tok': 0, 'context_tok': 0, 'model_calls': 0, 'user_calls': 0, 'tool_calls_count': 0 } }
    daily_stats = defaultdict(lambda: {
        'sessions': set(),
        'user_tok': 0,
        'model_tok': 0,
        'thinking_tok': 0,
        'tool_tok': 0,
        'context_tok': 0,
        'model_calls': 0,
        'user_calls': 0,
        'tool_calls_count': 0
    })

    # Per conversation stats:
    convo_stats = []

    SYSTEM_PROMPT_ESTIMATE = 3500  # Baseline system prompt + tools schema overhead per model turn

    processed_convos = 0
    total_steps_count = 0

    for idx, c_id in enumerate(convos):
        logs_dir = os.path.join(brain_dir, c_id, '.system_generated', 'logs')
        # Prefer transcript_full.jsonl if available and non-empty, else transcript.jsonl
        tf_path = os.path.join(logs_dir, 'transcript_full.jsonl')
        t_path = os.path.join(logs_dir, 'transcript.jsonl')

        target_file = None
        if os.path.exists(tf_path) and os.path.getsize(tf_path) > 0:
            target_file = tf_path
        elif os.path.exists(t_path) and os.path.getsize(t_path) > 0:
            target_file = t_path

        if not target_file:
            continue

        processed_convos += 1
        steps = []
        try:
            with open(target_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        steps.append(json.loads(line))
                    except:
                        pass
        except Exception as e:
            continue

        if not steps:
            continue

        c_user_tok = 0
        c_model_tok = 0
        c_thinking_tok = 0
        c_tool_tok = 0
        c_context_tok = 0
        c_dates = set()
        c_first_request = ""

        # Cumulative context tracker within this conversation
        current_history_tokens = SYSTEM_PROMPT_ESTIMATE

        for s in steps:
            total_steps_count += 1
            cat = s.get('created_at', '')
            date_str = cat[:10] if (cat and len(cat) >= 10 and cat[0].isdigit()) else 'unknown'
            if date_str != 'unknown':
                c_dates.add(date_str)
                daily_stats[date_str]['sessions'].add(c_id)

            stype = s.get('type')
            src = s.get('source')
            content = s.get('content', '')
            thinking = s.get('thinking', '')
            tc = s.get('tool_calls', [])

            step_tok = 0

            if src == 'USER_EXPLICIT' or stype == 'USER_INPUT':
                u_count = count_tok(content)
                c_user_tok += u_count
                daily_stats[date_str]['user_tok'] += u_count
                daily_stats[date_str]['user_calls'] += 1
                step_tok = u_count

                if not c_first_request and content:
                    # Clean up prompt for topic extraction
                    clean_req = content.replace('<USER_REQUEST>', '').replace('</USER_REQUEST>', '').strip()
                    first_line = clean_req.split('\n')[0].strip()
                    c_first_request = first_line[:70]

            elif src == 'MODEL' and stype == 'PLANNER_RESPONSE':
                # Model turn!
                # 1. Output content
                m_count = count_tok(content)
                # 2. Tool calls generated by model
                tc_count = count_tok(json.dumps(tc, ensure_ascii=False)) if tc else 0
                total_out = m_count + tc_count

                # 3. Thinking
                th_count = count_tok(thinking) if thinking else 0

                c_model_tok += total_out
                c_thinking_tok += th_count
                daily_stats[date_str]['model_tok'] += total_out
                daily_stats[date_str]['thinking_tok'] += th_count
                daily_stats[date_str]['model_calls'] += 1

                # 4. Context ingested by model on this turn
                c_context_tok += current_history_tokens
                daily_stats[date_str]['context_tok'] += current_history_tokens

                # Add this turn to history
                step_tok = total_out + th_count

            else:
                # Tool output or system message
                t_count = count_tok(content)
                c_tool_tok += t_count
                daily_stats[date_str]['tool_tok'] += t_count
                daily_stats[date_str]['tool_calls_count'] += 1
                step_tok = t_count

            current_history_tokens += step_tok

        c_total_unique = c_user_tok + c_model_tok + c_thinking_tok + c_tool_tok
        primary_date = min(c_dates) if c_dates else 'unknown'

        convo_stats.append({
            'id': c_id,
            'date': primary_date,
            'dates_count': len(c_dates),
            'steps': len(steps),
            'first_req': c_first_request or "(нет текста запроса)",
            'user_tok': c_user_tok,
            'model_tok': c_model_tok,
            'thinking_tok': c_thinking_tok,
            'tool_tok': c_tool_tok,
            'total_unique': c_total_unique,
            'context_tok': c_context_tok
        })

    # Sort dates
    sorted_dates = sorted([d for d in daily_stats.keys() if d != 'unknown'])

    # Build Daily Table
    daily_table = []
    tot_user = 0
    tot_model = 0
    tot_thinking = 0
    tot_tool = 0
    tot_unique = 0
    tot_context = 0
    tot_model_calls = 0

    for d in sorted_dates:
        row = daily_stats[d]
        u = row['user_tok']
        m = row['model_tok']
        th = row['thinking_tok']
        tl = row['tool_tok']
        uniq = u + m + th + tl
        ctx = row['context_tok']
        sess_cnt = len(row['sessions'])

        tot_user += u
        tot_model += m
        tot_thinking += th
        tot_tool += tl
        tot_unique += uniq
        tot_context += ctx
        tot_model_calls += row['model_calls']

        daily_table.append([
            d,
            sess_cnt,
            f"{u:,}",
            f"{m:,}",
            f"{th:,}",
            f"{tl:,}",
            f"{uniq:,}",
            f"{ctx:,}"
        ])

    # Save results to a structured JSON file as well
    result_data = {
        'summary': {
            'processed_conversations': processed_convos,
            'total_steps': total_steps_count,
            'total_dates': len(sorted_dates),
            'first_date': sorted_dates[0] if sorted_dates else None,
            'last_date': sorted_dates[-1] if sorted_dates else None,
            'tot_user_tokens': tot_user,
            'tot_model_tokens': tot_model,
            'tot_thinking_tokens': tot_thinking,
            'tot_tool_data_tokens': tot_tool,
            'tot_unique_payload_tokens': tot_unique,
            'tot_cumulative_context_tokens': tot_context,
            'tot_model_calls': tot_model_calls
        },
        'daily': [
            {
                'date': d,
                'sessions': len(daily_stats[d]['sessions']),
                'user_tokens': daily_stats[d]['user_tok'],
                'model_tokens': daily_stats[d]['model_tok'],
                'thinking_tokens': daily_stats[d]['thinking_tok'],
                'tool_tokens': daily_stats[d]['tool_tok'],
                'unique_tokens': daily_stats[d]['user_tok'] + daily_stats[d]['model_tok'] + daily_stats[d]['thinking_tok'] + daily_stats[d]['tool_tok'],
                'context_tokens': daily_stats[d]['context_tok']
            }
            for d in sorted_dates
        ],
        'top_conversations': sorted(convo_stats, key=lambda x: x['total_unique'], reverse=True)[:15]
    }

    out_json = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'antigravity_token_analysis.json')
    with open(out_json, 'w', encoding='utf-8') as f:
        json.dump(result_data, f, ensure_ascii=False, indent=2)

    print(f"\n================================================================================")
    print(f"                      ANTIGRAVITY 2.0 TOKEN USAGE REPORT                        ")
    print(f"================================================================================")
    print(f"Сессий проанализировано:        {processed_convos}")
    print(f"Всего шагов (сообщений/команд): {total_steps_count:,}")
    print(f"Период активности:              {sorted_dates[0] if sorted_dates else 'N/A'} — {sorted_dates[-1] if sorted_dates else 'N/A'}")
    print(f"--------------------------------------------------------------------------------")
    print(f"Входящие запросы (User):        {tot_user:>15,} токенов")
    print(f"Ответы модели (Model Output):   {tot_model:>15,} токенов")
    print(f"Рассуждения (Thinking CoT):     {tot_thinking:>15,} токенов")
    print(f"Данные инструментов (Tools):    {tot_tool:>15,} токенов")
    print(f"СУММАРНО УНИКАЛЬНЫХ ТОКЕНОВ:    {tot_unique:>15,} токенов  (~{tot_unique/1_000_000:.2f}M)")
    print(f"--------------------------------------------------------------------------------")
    print(f"НАКОПИТЕЛЬНЫЙ КОНТЕКСТ (Context):{tot_context:>14,} токенов  (~{tot_context/1_000_000:.2f}M)")
    print(f"(Сумма всех контекстов, переданных на вход модели за {tot_model_calls:,} вызовов)")
    print(f"================================================================================\n")

    # Print Top 10 Days
    days_by_tokens = sorted(daily_stats.items(), key=lambda x: (x[1]['user_tok'] + x[1]['model_tok'] + x[1]['thinking_tok'] + x[1]['tool_tok']), reverse=True)
    top_days_table = []
    for d, st in days_by_tokens[:10]:
        u = st['user_tok']
        m = st['model_tok']
        th = st['thinking_tok']
        tl = st['tool_tok']
        uniq = u + m + th + tl
        ctx = st['context_tok']
        top_days_table.append([d, len(st['sessions']), f"{u:,}", f"{m:,}", f"{th:,}", f"{tl:,}", f"{uniq:,}", f"{ctx:,}"])

    print("ТОП-10 САМЫХ НАГРУЖЕННЫХ ДНЕЙ:")
    headers = ["Дата", "Сессий", "User", "Model", "Thinking", "Tool Data", "Уникальных", "Контекст (Всего)"]
    print(tabulate(top_days_table, headers=headers, tablefmt="github"))
    print("\n")

    # Print Top 10 Conversations
    top_convos = sorted(convo_stats, key=lambda x: x['total_unique'], reverse=True)[:10]
    top_c_table = []
    for c in top_convos:
        top_c_table.append([
            c['id'][:8] + "...",
            c['date'],
            c['steps'],
            c['first_req'],
            f"{c['user_tok']:,}",
            f"{c['model_tok']:,}",
            f"{c['thinking_tok']:,}",
            f"{c['total_unique']:,}",
            f"{c['context_tok']:,}"
        ])

    print("ТОП-10 САМЫХ БОЛЬШИХ СЕССИЙ:")
    c_headers = ["ID", "Дата", "Шагов", "Тема / Первый запрос", "User", "Model", "Thinking", "Уникальных", "Контекст"]
    print(tabulate(top_c_table, headers=c_headers, tablefmt="github"))

if __name__ == '__main__':
    main()
